spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5411/orderservice
    username: orderservice
    password: orderservice
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    open-in-view: false

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  rabbitmq:
    username: admin
    password: admin
    port: 5682

server:
  port: 8001

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"